/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        "background": "hsl(var(--background))",
        "foreground": "hsl(var(--foreground))",
        "card": "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        "card-alt": "hsl(var(--card-alt))",
        "card-alt-foreground": "hsl(var(--card-alt-foreground))",
        "card-surface": "hsl(var(--card-surface))",
        "card-surface-foreground": "hsl(var(--card-surface-foreground))",
        "popover": "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        "primary": "hsl(var(--primary))",
        "primary-hover": "hsl(var(--primary-hover))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        "primary-ring": "hsl(var(--primary-ring))",
        "primary-light": "hsl(var(--primary-light))",
        "primary-light-hover": "hsl(var(--primary-light-hover))",
        "primary-light-foreground": "hsl(var(--primary-light-foreground))",
        "secondary": "hsl(var(--secondary))",
        "secondary-hover": "hsl(var(--secondary-hover))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        "secondary-ring": "hsl(var(--secondary-ring))",
        "secondary-light": "hsl(var(--secondary-light))",
        "secondary-light-hover": "hsl(var(--secondary-light-hover))",
        "secondary-light-foreground": "hsl(var(--secondary-light-foreground))",
        "danger": "hsl(var(--danger))",
        "danger-hover": "hsl(var(--danger-hover))",
        "danger-foreground": "hsl(var(--danger-foreground))",
        "danger-ring": "hsl(var(--danger-ring))",
        "danger-light": "hsl(var(--danger-light))",
        "danger-light-hover": "hsl(var(--danger-light-hover))",
        "danger-light-foreground": "hsl(var(--danger-light-foreground))",
        "success": "hsl(var(--success))",
        "success-hover": "hsl(var(--success-hover))",
        "success-foreground": "hsl(var(--success-foreground))",
        "success-ring": "hsl(var(--success-ring))",
        "success-ring-full": "hsl(var(--success-ring-full))",
        "success-light": "hsl(var(--success-light))",
        "success-light-hover": "hsl(var(--success-light-hover))",
        "success-light-foreground": "hsl(var(--success-light-foreground))",
        "warning": "hsl(var(--warning))",
        "warning-hover": "hsl(var(--warning-hover))",
        "warning-foreground": "hsl(var(--warning-foreground))",
        "warning-ring": "hsl(var(--warning-ring))",
        "warning-light": "hsl(var(--warning-light))",
        "warning-light-hover": "hsl(var(--warning-light-hover))",
        "warning-light-foreground": "hsl(var(--warning-light-foreground))",
        "info": "hsl(var(--info))",
        "info-hover": "hsl(var(--info-hover))",
        "info-foreground": "hsl(var(--info-foreground))",
        "info-ring": "hsl(var(--info-ring))",
        "info-light": "hsl(var(--info-light))",
        "info-light-hover": "hsl(var(--info-light-hover))",
        "info-light-foreground": "hsl(var(--info-light-foreground))",
        "muted": "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        "accent": "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        "destructive": "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        "border": "hsl(var(--border))",
        "input": "hsl(var(--input))",
        "field": "hsl(var(--field))",
        "field-ring": "hsl(var(--field-ring))",
        "field-ring-hover": "hsl(var(--field-ring-hover))",
        "field-foreground": "hsl(var(--field-foreground))",
        "radio": "hsl(var(--radio))",
        "radio-hover": "hsl(var(--radio-hover))",
        "radio-foreground": "hsl(var(--radio-foreground))",
        "ring": "hsl(var(--ring))",
        "radius": "0.5rem"
      },
    },
    fontFamily: {
      Poppins: ["Poppins", "sans-serif"],
    },
    container: {
      center: true,
      padding: "1rem",
    },
  },
  plugins: [],
};
