import animatePlugin from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        "card-alt": "hsl(var(--card-alt))",
        "card-alt-foreground": "hsl(var(--card-alt-foreground))",
        "card-surface": "hsl(var(--card-surface))",
        "card-surface-foreground": "hsl(var(--card-surface-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-hover": "hsl(var(--primary-hover))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        "primary-ring": "hsl(var(--primary-ring))",
        "primary-light": "hsla(var(--primary-light)/0.1)",
        "primary-light-hover": "hsla(var(--primary-light-hover)/0.2)",
        "primary-light-foreground": "hsl(var(--primary-light-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-hover": "hsl(var(--secondary-hover))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        "secondary-ring": "hsl(var(--secondary-ring))",
        "secondary-light": "hsla(var(--secondary-light)/0.1)",
        "secondary-light-hover": "hsla(var(--secondary-light-hover)/0.2)",
        "secondary-light-foreground": "hsl(var(--secondary-light-foreground))",
        danger: "hsl(var(--danger))",
        "danger-hover": "hsl(var(--danger-hover))",
        "danger-foreground": "hsl(var(--danger-foreground))",
        "danger-ring": "hsl(var(--danger-ring))",
        "danger-light": "hsla(var(--danger-light)/0.1)",
        "danger-light-hover": "hsla(var(--danger-light-hover)/0.2)",
        "danger-light-foreground": "hsl(var(--danger-light-foreground))",
        success: "hsl(var(--success))",
        "success-hover": "hsl(var(--success-hover))",
        "success-foreground": "hsl(var(--success-foreground))",
        "success-ring": "hsl(var(--success-ring))",
        "success-ring-full": "hsl(var(--success-ring-full))",
        "success-light": "hsla(var(--success-light)/0.1)",
        "success-light-hover": "hsla(var(--success-light-hover)/0.2)",
        "success-light-foreground": "hsl(var(--success-light-foreground))",
        warning: "hsl(var(--warning))",
        "warning-hover": "hsl(var(--warning-hover))",
        "warning-foreground": "hsl(var(--warning-foreground))",
        "warning-ring": "hsl(var(--warning-ring))",
        "warning-light": "hsla(var(--warning-light)/0.1)",
        "warning-light-hover": "hsla(var(--warning-light-hover)/0.2)",
        "warning-light-foreground": "hsl(var(--warning-light-foreground))",
        info: "hsl(var(--info))",
        "info-hover": "hsl(var(--info-hover))",
        "info-foreground": "hsl(var(--info-foreground))",
        "info-ring": "hsl(var(--info-ring))",
        "info-light": "hsla(var(--info-light)/0.1)",
        "info-light-hover": "hsla(var(--info-light-hover)/0.2)",
        "info-light-foreground": "hsl(var(--info-light-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        field: "hsl(var(--field))",
        "field-ring": "hsl(var(--field-ring))",
        "field-ring-hover": "hsl(var(--field-ring-hover))",
        "field-foreground": "hsl(var(--field-foreground))",
        radio: "hsl(var(--radio))",
        "radio-hover": "hsl(var(--radio-hover))",
        "radio-foreground": "hsl(var(--radio-foreground))",
        ring: "hsl(var(--ring))",
        radius: "0.5rem",
      },
    },
    fontFamily: {
      Poppins: ["Poppins", "sans-serif"],
    },
    container: {
      center: true,
      padding: "1rem",
    },
  },
  plugins: [animatePlugin],
};